# Generated by Django 4.2.9 on 2024-01-28 13:24

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "apps_reobjects",
            "0002_category_engineeringservices_fencing_foundation_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[],
            options={
                "verbose_name": "Категория объекта",
                "verbose_name_plural": "Категория объекта",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.category",),
        ),
        migrations.CreateModel(
            name="EngineeringServices",
            fields=[],
            options={
                "verbose_name": "Инженерные сети",
                "verbose_name_plural": "Инженерные сети",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.engineeringservices",),
        ),
        migrations.CreateModel(
            name="Fencing",
            fields=[],
            options={
                "verbose_name": "Ограждение участка",
                "verbose_name_plural": "Ограждение участка",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.fencing",),
        ),
        migrations.CreateModel(
            name="Foundation",
            fields=[],
            options={
                "verbose_name": "Тип фундамента",
                "verbose_name_plural": "Тип фундамента",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.foundation",),
        ),
        migrations.CreateModel(
            name="LandCategory",
            fields=[],
            options={
                "verbose_name": "Категория земель",
                "verbose_name_plural": "Категория земель",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.landcategory",),
        ),
        migrations.CreateModel(
            name="ObjectDescription",
            fields=[],
            options={
                "verbose_name": "Описание объекта",
                "verbose_name_plural": "Описание объекта",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.objectdescription",),
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[],
            options={
                "verbose_name": "Тип собственности",
                "verbose_name_plural": "Тип собственности",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.ownership",),
        ),
        migrations.CreateModel(
            name="ReliefArea",
            fields=[],
            options={
                "verbose_name": "Рельеф участка",
                "verbose_name_plural": "Рельеф участка",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.reliefarea",),
        ),
        migrations.CreateModel(
            name="TypeHouse",
            fields=[],
            options={
                "verbose_name": "Тип объекта",
                "verbose_name_plural": "Тип объекта",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.typehouse",),
        ),
        migrations.CreateModel(
            name="VillageFences",
            fields=[],
            options={
                "verbose_name": "Ограждения в поселке",
                "verbose_name_plural": "Ограждения в поселке",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.villagefences",),
        ),
        migrations.CreateModel(
            name="WallMaterial",
            fields=[],
            options={
                "verbose_name": "Материал стен",
                "verbose_name_plural": "Материал стен",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.wallmaterial",),
        ),
        migrations.CreateModel(
            name="WindowsOrientation",
            fields=[],
            options={
                "verbose_name": "Ориентация окон",
                "verbose_name_plural": "Ориентация окон",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.windowsorientation",),
        ),
    ]
