# Generated by Django 4.2.9 on 2024-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0015_remove_reobject_buildings_on_site"),
        ("apps_admin_attributes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinates",
            fields=[],
            options={
                "verbose_name": "Координаты",
                "verbose_name_plural": "Координаты",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.coordinates",),
        ),
    ]
