version: "3"

services:
  database:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    env_file:
      - 'infra/postgres/.env'
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - dashboard_networks

  backend:
    build:
      context: https://github.com/AlexandrMaltsevYDX/dashboard.git#main
      dockerfile: Dockerfile
    env_file:
      - 'infra/postgres/.env'
    entrypoint: /usr/local/bin/entrypoint.sh
    command: gunicorn --bind 0.0.0.0:8000 src.wsgi
    expose:
      - "8000"
    volumes:
      - .:/app
      - media:/app/media
      - static:/app/staticroot
    networks:
      - dashboard_networks

  nginx:
    image: nginx:1.24-alpine-slim
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./infra/nginx/:/etc/nginx/conf.d/
      - media:/media
      - static:/staticroot
    depends_on:
      - backend
    networks:
      - dashboard_networks

volumes:
  media:
    driver: local
  static:
    driver: local
  database_data:
    driver: local
networks:
  dashboard_networks:
    driver: bridge