# Generated by Django 4.2.9 on 2024-09-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0024_village_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="id",
            field=models.TextField(
                blank=True,
                help_text="Максимум 10 символов",
                max_length=10,
                null=True,
                verbose_name="ID посёлка",
            ),
        ),
    ]
