# Generated by Django 4.2.9 on 2024-01-27 20:59

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_reobjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.city",),
        ),
        migrations.CreateModel(
            name="Coordinates",
            fields=[],
            options={
                "verbose_name": "Координаты",
                "verbose_name_plural": "Координаты",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.coordinates",),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.country",),
        ),
        migrations.CreateModel(
            name="District",
            fields=[],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.district",),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.place",),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.region",),
        ),
        migrations.CreateModel(
            name="Street",
            fields=[],
            options={
                "verbose_name": "Улица",
                "verbose_name_plural": "Улицы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.street",),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.tag",),
        ),
    ]
